name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.Ss2468101314! }}" | docker login -u "${{ secrets.sarasalah24 }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.sarasalah24 }}/my-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.sarasalah24 }}/my-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with: 
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        
